### ISSUE TITLE
AttributeError: 'PrivateKey' object has no attribute 'sign_event'

### ISSUE THREAD

**Issue by grubles** [jeffthibault/python-nostr#38]
I'm hobbling together a script to post events and am running into this error. The script also includes the `watchdog` module for monitoring a directory for new files. Is there some sort of "events" name collision somewhere maybe? I used `pprint` to dump the `PrivateKey` object's attributes. The event looks like it's created successfully but I'm unable to actually sign it. This is with python 3.9.5.

```
{'content': 'Doc Hodlday sends his regards ',
 'created_at': 1674353522,
 'id': '818a24313b54cc98234cbc11edbf9ae11631405083251341631c54351d80810a',
 'kind': <EventKind.TEXT_NOTE: 1>,
 'public_key': '0000000025a7ccbf6bd0c0a5a1856d78f2e9f08c778b779d35e81b5ea3f77edf',
 'signature': None,
 'tags': []}
 ```
 ```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/home/user/.local/lib/python3.9/site-packages/watchdog/observers/api.py", line 205, in run
    self.dispatch_events(self.event_queue)
  File "/home/user/.local/lib/python3.9/site-packages/watchdog/observers/api.py", line 381, in dispatch_events
    handler.dispatch(event)
  File "/home/user/.local/lib/python3.9/site-packages/watchdog/events.py", line 271, in dispatch
    self.on_any_event(event)
  File "/home/user/satbot/telegram.py", line 80, in on_any_event
    private_key.sign_event(nostr_event)
AttributeError: 'PrivateKey' object has no attribute 'sign_event'
```

**Comment by grubles** [comment]
I just realized I might not be using master because I installed the `nostr` module via `pip`...
