### ISSUE TITLE
relay issue

### ISSUE THREAD

**Issue by augustfr** [jeffthibault/python-nostr#64]
```from nostr.key import PrivateKey
import json
import ssl
import time
from nostr.relay_manager import RelayManager

private_key = PrivateKey()
public_key = private_key.public_key

senderPrivateKey = PrivateKey()
senderPublicKey = senderPrivateKey.public_key

receiverPrivateKey = PrivateKey()
receiverPublicKey = receiverPrivateKey.public_key

sharedSecretPrivate = PrivateKey()
sharedSecretPublic = sharedSecretPrivate.public_key

print(f"Private key: {sharedSecretPrivate.bech32()}")
print(f"Public key: {sharedSecretPublic.bech32()}")

relay_manager = RelayManager()
relay_manager.add_relay("wss://nostr-pub.wellorder.net")
relay_manager.add_relay("wss://relay.damus.io")
relay_manager.open_connections({"cert_reqs": ssl.CERT_NONE}) # NOTE: This disables ssl certificate verification
time.sleep(1.25) # allow the connections to open

while relay_manager.message_pool.has_notices():
  notice_msg = relay_manager.message_pool.get_notice()
  print(notice_msg.content)
  
relay_manager.close_connections()```


When I run this, I'm getting the following error: 

Traceback (most recent call last):
  File "/Users/august/Documents/Nostr/python-nostr/nostr.py", line 5, in <module>
    from nostr.relay_manager import RelayManager
  File "/Users/august/Documents/Nostr/python-nostr/nostr/relay_manager.py", line 11, in <module>
    from .relay import Relay, RelayPolicy, RelayProxyConnectionConfig
  File "/Users/august/Documents/Nostr/python-nostr/nostr/relay.py", line 33, in <module>
    @dataclass
     ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1221, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 1211, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 959, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/dataclasses.py", line 816, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'nostr.relay.RelayPolicy'> for field policy is not allowed: use default_factory

Any ideas?

**Comment by AveragePythonEnjoyer29** [comment]
did you clone the git repo, and used that?
if that's the case, you need to install it using pip: `pip install nostr`

**Comment by augustfr** [comment]
I cloned the git repo but have also ran pip install nostr (both before I ran into this issue)

**Comment by AveragePythonEnjoyer29** [comment]
> I cloned the git repo but have also ran pip install nostr (both before I ran into this issue)

it seems like you're still importing the one you cloned from git. Try removing both before installing the one from pip again

**Comment by augustfr** [comment]
and then how would I change the import statements to still work properly?

**Comment by AveragePythonEnjoyer29** [comment]
> and then how would I change the import statements to still work properly?

just do `import nostr` like you normally would

**Comment by augustfr** [comment]
Yeah that is what I have but it's now saying "NameError: name 'PrivateKey' is not defined"

**Comment by AveragePythonEnjoyer29** [comment]
> Yeah that is what I have but it's now saying "NameError: name 'PrivateKey' is not defined"

you sure you're importing everything correctly?
this is what my code looks like:
```python
from nostr.key import PrivateKey
from nostr.filter import Filter, Filters
from nostr.event import Event, EventKind
from nostr.relay_manager import RelayManager
from nostr.message_type import ClientMessageType
```

**Comment by AveragePythonEnjoyer29** [comment]
it seems like the github version and actual pypi version differ a lot, i miss the react functionary and other stuff too

**Comment by augustfr** [comment]
Just swapped it to be how you have it and now I'm getting 'ModuleNotFoundError: No module named 'nostr.key'; 'nostr' is not a package' which is why I did the git clone option instead originally.

**Comment by AveragePythonEnjoyer29** [comment]
weird, can you do `pip install nostr`? If it says it already exists something is wrong with your python

**Comment by augustfr** [comment]
Says everything is already satisfied.

**Comment by augustfr** [comment]
<img width="1220" alt="Screenshot 2023-02-11 at 2 09 56 PM" src="https://user-images.githubusercontent.com/68298953/218283178-18c0ffae-6ed8-4173-b1ab-d256fc9742cb.png">

**Comment by AveragePythonEnjoyer29** [comment]
try `python3 -m pip install nostr`

**Comment by augustfr** [comment]
Just ran that. Getting the same issue still 

```Traceback (most recent call last):
  File "/Users/august/Documents/Nostr/nostr.py", line 4, in <module>
    from nostr.key import PrivateKey
  File "/Users/august/Documents/Nostr/nostr.py", line 4, in <module>
    from nostr.key import PrivateKey
ModuleNotFoundError: No module named 'nostr.key'; 'nostr' is not a package```

**Comment by AveragePythonEnjoyer29** [comment]
i see why, you named your file `nostr` which confuses Python. Rename it and it should work

**Comment by AveragePythonEnjoyer29** [comment]
it's trying to import the classes from your file, because it think that that is the module

**Comment by augustfr** [comment]
yep wow that fixed it. Thanks for helping out so much!

**Comment by AveragePythonEnjoyer29** [comment]
cheers!
