### ISSUE TITLE
ValueError decoding Type 4 DM: "Invalid padding bytes."

### ISSUE THREAD

**Issue by f321x** [jeffthibault/python-nostr#68]
When trying to decode a received Type 4 DM from Amethyst or Astral i get a Value Error "Invalid padding bytes." 
(using Nostr 0.0.2 from pip)

Code i used:
```
if event_msg.event.kind == 4:
                user_pk = event_msg.event.public_key
                content = PrivateKey().decrypt_message(event_msg.event.content, user_pk)
                print(content)
```

after receiving a type 4 dm it returns the following error:

> Traceback (most recent call last):
>   File "/home/benutzer/PycharmProjects/X/testing.py", line 66, in <module>
>     nostr_dalle()
>   File "/home/benutzer/PycharmProjects/X/testing.py", line 58, in nostr_dalle
>     content = PrivateKey().decrypt_message(event_msg.event.content, user_pk)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/benutzer/PycharmProjects/X/venv/lib/python3.11/site-packages/nostr/key.py", line 93, in decrypt_message
>     unpadded_data = unpadder.update(decrypted_message) + unpadder.finalize()
>                                                          ^^^^^^^^^^^^^^^^^^^
>   File "/home/benutzer/PycharmProjects/X/venv/lib64/python3.11/site-packages/cryptography/hazmat/primitives/padding.py", line 159, in finalize
>     result = _byte_unpadding_check(
>              ^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/benutzer/PycharmProjects/X/venv/lib64/python3.11/site-packages/cryptography/hazmat/primitives/padding.py", line 101, in _byte_unpadding_check
>     raise ValueError("Invalid padding bytes.")
> ValueError: Invalid padding bytes.

Am i doing this wrong or could this be a bug?

**Comment by f321x** [comment]
Oh ok makes sense, thanks. I'll try it.

**Comment by f321x** [comment]
Worked, my fault. Thanks for the help.
Correct code in my case is:

```
private_key = PrivateKey().from_nsec("My nostr nsec private key")
...
if event_msg.event.kind == 4:
                user_pk = event_msg.event.public_key
                content = private_key.decrypt_message(event_msg.event.content, user_pk)
                print(content)
```
